### PRUEBA: POST a user
POST http://localhost:3000/api/users
content-type: application/json

{
	"email": "random@ass.email",
	"username": "RandomAssUser",
	"password": "password",
	"address": "Ohio",
	"imageUrl": "https://i.blogs.es/d225d6/skibidi-toilet-wiki/500_333.jpeg",
	"role": "user"
}

### GET all users
GET http://localhost:3000/api/users

### GET a user with uuid
GET http://localhost:3000/api/users/d7cd8205-a92f-4fed-81bd-29b10c134f0f

### DELETE user
DELETE http://localhost:3000/api/users/63cf7a4c-884e-48e8-8be4-96d75ff3c51c

### PRUEBA: POST a user
PUT http://localhost:3000/api/users/d7cd8205-a92f-4fed-81bd-29b10c134f0f
content-type: application/json

{
	"email": "random@as.email",
	"username": "RandomAsUser",
	"password": "password",
	"address": "Ohio",
	"imageUrl": "https://i.blogs.es/d225d6/skibidi-toilet-wiki/500_333.jpeg",
	"role": "user"
}

### Login
POST http://localhost:3000/api/users/login
content-type: application/json

{
	"email": "random@ass.email",
	"password": "password"
}

### Signup
POST http://localhost:3000/api/users/signup
content-type: application/json

{
	"email": "inaki.medina@iteso.mx",
	"username": "Marine Lord",
	"password": "iteso",
	"address": "iteso"
}

### Get token
GET http://localhost:3000/api/token


### Store token
POST http://localhost:3000/api/token
content-type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmRvbUBhc3MuZW1haWwiLCJ1c2VybmFtZSI6IlJhbmRvbUFzc1VzZXIiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMjY0MjA2OX0.nlTm83UEoTtjSIscUl1ndtYXl--GcAXjMMhFRJZwBrg"
}
